### ISSUE TITLE
Introduce optional placeholder

### ISSUE THREAD

**Issue by szaghi** [rasbt/markdown-toclify#7]
Hi all,

the present behavior of markdown-toclify is to place TOC to the very first line of the output. Sometimes,
it can be more versatile to have the opportunity to place the TOC elsewhere. Let us consider the following example:

```markdown
# Title

## Chapter 1

## Chapter 2
```
the present default output should be something like:

```markdown
- [Title](#title)
    - [Chapter 1](#chapter-1)
    - [Chapter 2](#chapter-2)

# Title

## Chapter 1

## Chapter 2
```
It would be very nice if one can specify (optionally) a different placement as
```markdown
# Title

## Table of Contents
- [Title](#title)
    - [Chapter 1](#chapter-1)
    - [Chapter 2](#chapter-2)

## Chapter 1

## Chapter 2
```

For example using a *user-defined* placeholder:

```markdown
# Title

![toc]("Table of Contents")

## Chapter 1

## Chapter 2
```

The syntax is just the first one I thought to, not a real suggestion. This behavior can be triggered by a command line argument as:
```shell
./markdown_toclify.py -place toc
``` 
where `toc` is the name used for the user-define placeholder.

This is only a suggestion that I think can improve the tool versatility for easily integrating into an automated framework.

My best regards.

**Comment by rasbt** [comment]
I also like this one! I wouldn't use `![toc]` though since it overlaps with the`![]` syntax for images.

Maybe something like `$[toc]$`?
I would say that `./markdown_toclify.py -place toc` could look for the string inside `$[]$` and replace it with the actual table of contents, e.g., so that a use can do 

`$[toc]$` & `./markdown_toclify.py -place toc`

or 

`$[some-string]$` & `./markdown_toclify.py -place some-string`

**Comment by szaghi** [comment]
Hi Sebastian,

thank you for quick and kind replay, mine are only suggestions for an already great tool :-)

You are completely right, it is very nice to collapse the placeholder and the string of the TOC definition. Moreover this could allow the user to choice the TOC heading level, e.g.

```markdown

# Title

### $[my-toc]$

## Part 1

### Chapter 1

#### Section 1

## Part 2

### Chapter 2
```
and `./markdown_toclify.py -place 'my-toc'` should produce:

```markdown

# Title

### my-toc
- [Title](#title)
    - [Part 1](#part-1)
        - [Chapter 1](#chapter-1)
            - [Section 1](#section-1)
    - [Part 2](#part-2)
        - [Chapter 2](#chapter-2)

## Part 1

### Chapter 1

#### Section 1

## Part 2

### Chapter 2
```
Thank you very much for sharing your work.

P.S. Take my issues only as suggestions, I know you are very busy.

**Comment by rasbt** [comment]
Also this one is added now. Thx!

**Comment by szaghi** [comment]
Wonderful!

You are great!
