### ISSUE TITLE
Heading level exclusion

### ISSUE THREAD

**Issue by szaghi** [rasbt/markdown-toclify#8]
Hi all,

in order to improve the flexibility of the tool for easily integrating it into an automated framework, it would be very nice to have the possibility to exclude a (some) heading level(s) from the TOC.

The present default behavior is to capture all heading levels, e.g. 

```markdown
# Title

## Chapter 1

## Chapter 2

### Section 1
```
will generate:
```markdown
- [Title](#title)
    - [Chapter 1](#chapter-1)
    - [Chapter 2](#chapter-2)
        - [Section 1](#section-1)
# Title

## Chapter 1

## Chapter 2

### Section 1
```
It would very appreciated to have the possibility to exclude one (or more) heading levels, e.g.
```shell
./markdown_toclify.py -exclude_h 1 3
```
will exclude the first and the third levels producing:
```markdown
- [Chapter 1](#chapter-1)
- [Chapter 2](#chapter-2)

# Title

## Chapter 1

## Chapter 2

### Section 1
```
This enhancement will greatly favorite the easily integration into an automated framework, I think.

My best regards.

**Comment by rasbt** [comment]
Hi, Stefano, I really like this idea; sounds very useful indeed! It should not be quite straight forward to add such a feature. I am currently very busy with other things (many work projects, and writing a machine learning book in my freetime), but I can add sth like this for sure! Thanks!

**Comment by szaghi** [comment]
Thank you for kind replay. 

If you need help I can try, but I am not a good Pythonic programmer.

**Comment by rasbt** [comment]
The features has been added. Thanks for the suggestions again!

**Comment by szaghi** [comment]
Great again!
