### ISSUE TITLE
Misleading formatting in screenshot

### ISSUE THREAD

**Issue by kerstin** [rasbt/markdown-toclify#9]
Hi there, I just tried your script but failed to get the results I expected because I used a different flavour of Markdown. Not your fault, but looking at your screenshots I noticed that one of them contains equally incorrect Markdown, which is misleading.

The headline created by your script on the left side of this picture: https://github.com/rasbt/markdown-toclify/blob/master/images/test_output_2.png would need to formatted ```# Table of Contents``` (with a space following the hash sign) to actually display as a headline in CommonMark. Headlines not formatted that way are not ignored but in fact seem to get wiped out entirely by your script. (;

**Comment by rasbt** [comment]
Thanks for pointing it out Kerstin! The screenshot was indeed misleading and the stripping of the headers in absence of the whitespace between "#" and the first letter was indeed a bug!
